In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# **DF Full**

In [ ]:
file = '/content/drive/MyDrive/Colab Notebooks/Dataset/Homework-DataFrame-Dataset.xlsx'
df = pd.read_excel(file)

In [ ]:
df.head(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,Paid Date,Order Number,First Name,Last Name,Meta Category,Product Name,Transaction Amount,Seller Discount,Sales Discount,Delivery Fee,Other Discount
1,NaN,20170724,201707240088517,elvride,aries,Babies/ Kids,Pineapple Hat Anak Ala Korea - 6M - 4Y - Unise...,300000,153000,10200,9000,0
2,NaN,20170701,201707018889790,BASIR,Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,0,0,0
3,NaN,20170707,201707079264675,Citra,Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,700,0,0
4,NaN,20170720,201707209945714,Dian,Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,5900,0,0
5,NaN,20170722,201707220002354,rizal,Tamba,Gadget/ Komputer,Samsung Galaxy Note 5 Gold,81000,0,5600,0,0
6,NaN,20170714,201707149671962,fauzannor,andri,Service/ Mokado,Pulsa Indosat REG 50.000,149000,0,10400,9000,0
7,NaN,20170703,201707039018928,della,Suryo,Service/ Mokado,Pulsa Indosat REG 50.000,90000,48100,2900,0,0
8,NaN,20170707,201707079291011,Sri,Oki,Service/ Mokado,Pulsa Indosat REG 50.000,180000,96200,5800,0,0
9,NaN,20170703,201706218386960,Irene,Hana,Service/ Mokado,[BUKBER HEMAT] Es Teler 77 : Es Teler,300000,156400,10000,9000,0

In [ ]:
df.shape

(12001, 12)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12001 entries, 0 to 12000
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   0 non-null      float64
 1   Unnamed: 1   12001 non-null  object
 2   Unnamed: 2   12001 non-null  object
 3   Unnamed: 3   11997 non-null  object
 4   Unnamed: 4   11997 non-null  object
 5   Unnamed: 5   12001 non-null  object
 6   Unnamed: 6   12001 non-null  object
 7   Unnamed: 7   12001 non-null  object
 8   Unnamed: 8   12001 non-null  object
 9   Unnamed: 9   12001 non-null  object
 10  Unnamed: 10  12001 non-null  object
 11  Unnamed: 11  12001 non-null  object
dtypes: float64(1), object(11)
memory usage: 1.1+ MB

In [ ]:
df.describe()

       Unnamed: 0
count         0.0
mean          NaN
std           NaN
min           NaN
25%           NaN
50%           NaN
75%           NaN
max           NaN

In [ ]:
df.isna().sum()

Unnamed: 0     12001
Unnamed: 1         0
Unnamed: 2         0
Unnamed: 3         4
Unnamed: 4         4
Unnamed: 5         0
Unnamed: 6         0
Unnamed: 7         0
Unnamed: 8         0
Unnamed: 9         0
Unnamed: 10        0
Unnamed: 11        0
dtype: int64

In [ ]:
df.nunique()

Unnamed: 0         0
Unnamed: 1       166
Unnamed: 2     12001
Unnamed: 3      6561
Unnamed: 4      6561
Unnamed: 5         9
Unnamed: 6      4163
Unnamed: 7      1329
Unnamed: 8      1058
Unnamed: 9       521
Unnamed: 10       25
Unnamed: 11       31
dtype: int64

In [ ]:
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,Paid Date,Order Number,First Name,Last Name,Meta Category,Product Name,Transaction Amount,Seller Discount,Sales Discount,Delivery Fee,Other Discount
1,NaN,20170724,201707240088517,elvride,aries,Babies/ Kids,Pineapple Hat Anak Ala Korea - 6M - 4Y - Unise...,300000,153000,10200,9000,0
2,NaN,20170701,201707018889790,BASIR,Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,0,0,0
3,NaN,20170707,201707079264675,Citra,Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,700,0,0
4,NaN,20170720,201707209945714,Dian,Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,5900,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
11996,NaN,20171201,201712012704898,Fitrah,gina,Service/ Mokado,"Xtra Combo 12GB, 30hr",333000,300000,2300,0,0
11997,NaN,20171203,201712032723513,Djebeng,Shinta,Service/ Mokado,"Xtra Combo 12GB, 30hr",280000,222500,0,0,0
11998,NaN,20171204,201712042740205,Amik,Elan,Home/ Food,Kreta - Kripik Tempe Indonesia - Rasa Jomblo d...,150000,81000,4800,0,0
11999,NaN,20171207,201712072778621,Anna,asih,Gadget/ Komputer,Samsung Galaxy J5 Pro Garansi Resmi Special Price,475000,400000,0,0,0
12000,NaN,20171205,201712052746101,nidyah,ayi,Service/ Mokado,[SERBU 11.12] Share Tea Cocoa Rocksalt & Chees...,475000,400000,20000,17000,0

# **DF “Paid-Transaction” dan “Seller”**

In [ ]:
data_paid_transaction = pd.read_excel(file, sheet_name="Paid-Transaction")
data_seller = pd.read_excel(file, sheet_name="Seller")

In [ ]:
data_paid_transaction

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,Paid Date,Order Number,First Name,Last Name,Meta Category,Product Name,Transaction Amount,Seller Discount,Sales Discount,Delivery Fee,Other Discount
1,NaN,20170724,201707240088517,elvride,aries,Babies/ Kids,Pineapple Hat Anak Ala Korea - 6M - 4Y - Unise...,300000,153000,10200,9000,0
2,NaN,20170701,201707018889790,BASIR,Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,0,0,0
3,NaN,20170707,201707079264675,Citra,Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,700,0,0
4,NaN,20170720,201707209945714,Dian,Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,5900,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
11996,NaN,20171201,201712012704898,Fitrah,gina,Service/ Mokado,"Xtra Combo 12GB, 30hr",333000,300000,2300,0,0
11997,NaN,20171203,201712032723513,Djebeng,Shinta,Service/ Mokado,"Xtra Combo 12GB, 30hr",280000,222500,0,0,0
11998,NaN,20171204,201712042740205,Amik,Elan,Home/ Food,Kreta - Kripik Tempe Indonesia - Rasa Jomblo d...,150000,81000,4800,0,0
11999,NaN,20171207,201712072778621,Anna,asih,Gadget/ Komputer,Samsung Galaxy J5 Pro Garansi Resmi Special Price,475000,400000,0,0,0
12000,NaN,20171205,201712052746101,nidyah,ayi,Service/ Mokado,[SERBU 11.12] Share Tea Cocoa Rocksalt & Chees...,475000,400000,20000,17000,0

In [ ]:
data_seller

       Unnamed: 0        Unnamed: 1    Unnamed: 2
0             NaN      Order Number        Seller
1             NaN  201707209929420   Global Phone
2             NaN  201707129550097         E-shop
3             NaN  201707039056021    twelven com
4             NaN  201707099376522       GRAMEDIA
...           ...               ...           ...
11996         NaN  201712042733301         E-Bold
11997         NaN  201711292684084   Luckykorea88
11998         NaN  201712072774578       GAU SHOP
11999         NaN  201712032722038    Farida Toko
12000         NaN  201712112833370    Mullia Cell

[12001 rows x 3 columns]

In [ ]:
data_paid_transaction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12001 entries, 0 to 12000
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   0 non-null      float64
 1   Unnamed: 1   12001 non-null  object
 2   Unnamed: 2   12001 non-null  object
 3   Unnamed: 3   11997 non-null  object
 4   Unnamed: 4   11997 non-null  object
 5   Unnamed: 5   12001 non-null  object
 6   Unnamed: 6   12001 non-null  object
 7   Unnamed: 7   12001 non-null  object
 8   Unnamed: 8   12001 non-null  object
 9   Unnamed: 9   12001 non-null  object
 10  Unnamed: 10  12001 non-null  object
 11  Unnamed: 11  12001 non-null  object
dtypes: float64(1), object(11)
memory usage: 1.1+ MB

In [ ]:
data_seller.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12001 entries, 0 to 12000
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  0 non-null      float64
 1   Unnamed: 1  12001 non-null  object
 2   Unnamed: 2  12001 non-null  object
dtypes: float64(1), object(2)
memory usage: 281.4+ KB

In [ ]:
data_paid_transaction.describe()

       Unnamed: 0
count         0.0
mean          NaN
std           NaN
min           NaN
25%           NaN
50%           NaN
75%           NaN
max           NaN

In [ ]:
data_seller.describe()

       Unnamed: 0
count         0.0
mean          NaN
std           NaN
min           NaN
25%           NaN
50%           NaN
75%           NaN
max           NaN

In [ ]:
data_paid_transaction.isna().sum()

Unnamed: 0     12001
Unnamed: 1         0
Unnamed: 2         0
Unnamed: 3         4
Unnamed: 4         4
Unnamed: 5         0
Unnamed: 6         0
Unnamed: 7         0
Unnamed: 8         0
Unnamed: 9         0
Unnamed: 10        0
Unnamed: 11        0
dtype: int64

In [ ]:
data_seller.isna().sum()

Unnamed: 0    12001
Unnamed: 1        0
Unnamed: 2        0
dtype: int64

In [ ]:
data_paid_transaction.nunique()

Unnamed: 0         0
Unnamed: 1       166
Unnamed: 2     12001
Unnamed: 3      6561
Unnamed: 4      6561
Unnamed: 5         9
Unnamed: 6      4163
Unnamed: 7      1329
Unnamed: 8      1058
Unnamed: 9       521
Unnamed: 10       25
Unnamed: 11       31
dtype: int64

In [ ]:
data_seller.nunique()

Unnamed: 0        0
Unnamed: 1    12001
Unnamed: 2     1642
dtype: int64

In [ ]:
data_paid_transaction['Unnamed: 3'].unique()

array(['First Name', 'elvride', 'BASIR', ..., 'Kevin', 'Djebeng', 'Amik'],
      dtype=object)

In [ ]:
data_paid_transaction['Unnamed: 4'].unique()

array(['Last Name', 'aries', 'Ninuk', ..., 'Shasa', 'NILA', 'Elan'],
      dtype=object)

In [ ]:
data_paid_transaction = data_paid_transaction.drop(columns=["Unnamed: 0"])
data_paid_transaction.columns = data_paid_transaction.iloc[0]
data_paid_transaction = data_paid_transaction.drop(index=0)

In [ ]:
data_paid_transaction

,Paid Date,Order Number,First Name,Last Name,Meta Category,Product Name,Transaction Amount,Seller Discount,Sales Discount,Delivery Fee,Other Discount
1,20170724,201707240088517,elvride,aries,Babies/ Kids,Pineapple Hat Anak Ala Korea - 6M - 4Y - Unise...,300000,153000,10200,9000,0
2,20170701,201707018889790,BASIR,Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,0,0,0
3,20170707,201707079264675,Citra,Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,700,0,0
4,20170720,201707209945714,Dian,Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,5900,0,0
5,20170722,201707220002354,rizal,Tamba,Gadget/ Komputer,Samsung Galaxy Note 5 Gold,81000,0,5600,0,0
...,...,...,...,...,...,...,...,...,...,...,...
11996,20171201,201712012704898,Fitrah,gina,Service/ Mokado,"Xtra Combo 12GB, 30hr",333000,300000,2300,0,0
11997,20171203,201712032723513,Djebeng,Shinta,Service/ Mokado,"Xtra Combo 12GB, 30hr",280000,222500,0,0,0
11998,20171204,201712042740205,Amik,Elan,Home/ Food,Kreta - Kripik Tempe Indonesia - Rasa Jomblo d...,150000,81000,4800,0,0
11999,20171207,201712072778621,Anna,asih,Gadget/ Komputer,Samsung Galaxy J5 Pro Garansi Resmi Special Price,475000,400000,0,0,0
12000,20171205,201712052746101,nidyah,ayi,Service/ Mokado,[SERBU 11.12] Share Tea Cocoa Rocksalt & Chees...,475000,400000,20000,17000,0

In [ ]:
data_seller = data_seller.drop(columns=["Unnamed: 0"])
data_seller.columns = data_seller.iloc[0]
data_seller = data_seller.drop(index=0)

In [ ]:
data_seller

0          Order Number        Seller
1      201707209929420   Global Phone
2      201707129550097         E-shop
3      201707039056021    twelven com
4      201707099376522       GRAMEDIA
5      201707028956707         E-Bold
...                 ...           ...
11996  201712042733301         E-Bold
11997  201711292684084   Luckykorea88
11998  201712072774578       GAU SHOP
11999  201712032722038    Farida Toko
12000  201712112833370    Mullia Cell

[12000 rows x 2 columns]

In [ ]:
data_paid_transaction["Order Number"] = data_paid_transaction["Order Number"].astype(str)
data_seller["Order Number"] = data_seller["Order Number"].astype(str)

In [ ]:
data_paid_transaction["Order Number"] = data_paid_transaction["Order Number"].str.replace(r'\D', '', regex=True)
data_seller["Order Number"] = data_seller["Order Number"].str.replace(r'\D', '', regex=True)

In [ ]:
data_paid_transaction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 1 to 12000
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Paid Date           12000 non-null  object
 1   Order Number        12000 non-null  object
 2   First Name          11996 non-null  object
 3   Last Name           11996 non-null  object
 4   Meta Category       12000 non-null  object
 5   Product Name        12000 non-null  object
 6   Transaction Amount  12000 non-null  object
 7   Seller Discount     12000 non-null  object
 8   Sales Discount      12000 non-null  object
 9   Delivery Fee        12000 non-null  object
 10  Other Discount      12000 non-null  object
dtypes: object(11)
memory usage: 1.0+ MB

In [ ]:
data_seller.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 1 to 12000
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order Number  12000 non-null  object
 1   Seller        12000 non-null  object
dtypes: object(2)
memory usage: 187.6+ KB

In [ ]:
merged_data = data_paid_transaction.merge(data_seller, left_on="Order Number", right_on="Order Number", how="inner")

In [ ]:
merged_data

,Paid Date,Order Number,First Name,Last Name,Meta Category,Product Name,Transaction Amount,Seller Discount,Sales Discount,Delivery Fee,Other Discount,Seller
0,20170724,201707240088517,elvride,aries,Babies/ Kids,Pineapple Hat Anak Ala Korea - 6M - 4Y - Unise...,300000,153000,10200,9000,0,Babymaniashop
1,20170701,201707018889790,BASIR,Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,0,0,0,E-Bold
2,20170707,201707079264675,Citra,Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,700,0,0,XLmystore
3,20170720,201707209945714,Dian,Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,5900,0,0,Ennwen Online Store
4,20170722,201707220002354,rizal,Tamba,Gadget/ Komputer,Samsung Galaxy Note 5 Gold,81000,0,5600,0,0,Media Gadget
...,...,...,...,...,...,...,...,...,...,...,...,...
11995,20171201,201712012704898,Fitrah,gina,Service/ Mokado,"Xtra Combo 12GB, 30hr",333000,300000,2300,0,0,XLmystore
11996,20171203,201712032723513,Djebeng,Shinta,Service/ Mokado,"Xtra Combo 12GB, 30hr",280000,222500,0,0,0,XLmystore
11997,20171204,201712042740205,Amik,Elan,Home/ Food,Kreta - Kripik Tempe Indonesia - Rasa Jomblo d...,150000,81000,4800,0,0,Kreta Chips
11998,20171207,201712072778621,Anna,asih,Gadget/ Komputer,Samsung Galaxy J5 Pro Garansi Resmi Special Price,475000,400000,0,0,0,Erafone.com
11999,20171205,201712052746101,nidyah,ayi,Service/ Mokado,[SERBU 11.12] Share Tea Cocoa Rocksalt & Chees...,475000,400000,20000,17000,0,Serbu Seller

# **No 1**

In [ ]:
# Menggabungkan kolom "First Name" dan "Last Name" dengan format "title case" menjadi kolom "Full Name"
# str.title() digunakan untuk membuat "title case,"
title_case = merged_data["First Name"].str.title() + " " + merged_data["Last Name"].str.title()

# Mendapatkan indeks kolom "Last Name" dengan cara
# menggunakan get_loc untuk mencari indeks (posisi) dari elemen Last Name
last_name_index = merged_data.columns.get_loc("Last Name")

# Sisipkan kolom "Full Name" setelah kolom "Last Name" menggunakan + 1
merged_data.insert(last_name_index + 1, "Full Name", title_case)

In [ ]:
merged_data

,Paid Date,Order Number,First Name,Last Name,Full Name,Meta Category,Product Name,Transaction Amount,Seller Discount,Sales Discount,Delivery Fee,Other Discount,Seller
0,20170724,201707240088517,elvride,aries,Elvride Aries,Babies/ Kids,Pineapple Hat Anak Ala Korea - 6M - 4Y - Unise...,300000,153000,10200,9000,0,Babymaniashop
1,20170701,201707018889790,BASIR,Ninuk,Basir Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,0,0,0,E-Bold
2,20170707,201707079264675,Citra,Ardi,Citra Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,700,0,0,XLmystore
3,20170720,201707209945714,Dian,Renaldi,Dian Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,5900,0,0,Ennwen Online Store
4,20170722,201707220002354,rizal,Tamba,Rizal Tamba,Gadget/ Komputer,Samsung Galaxy Note 5 Gold,81000,0,5600,0,0,Media Gadget
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,20171201,201712012704898,Fitrah,gina,Fitrah Gina,Service/ Mokado,"Xtra Combo 12GB, 30hr",333000,300000,2300,0,0,XLmystore
11996,20171203,201712032723513,Djebeng,Shinta,Djebeng Shinta,Service/ Mokado,"Xtra Combo 12GB, 30hr",280000,222500,0,0,0,XLmystore
11997,20171204,201712042740205,Amik,Elan,Amik Elan,Home/ Food,Kreta - Kripik Tempe Indonesia - Rasa Jomblo d...,150000,81000,4800,0,0,Kreta Chips
11998,20171207,201712072778621,Anna,asih,Anna Asih,Gadget/ Komputer,Samsung Galaxy J5 Pro Garansi Resmi Special Price,475000,400000,0,0,0,Erafone.com
11999,20171205,201712052746101,nidyah,ayi,Nidyah Ayi,Service/ Mokado,[SERBU 11.12] Share Tea Cocoa Rocksalt & Chees...,475000,400000,20000,17000,0,Serbu Seller

# **No 2**

In [ ]:
# Menghitung Gross Merchandise Value (GMV) dengan operasi aritmatika
gmv_hitung = merged_data["Transaction Amount"].astype(int) - merged_data["Seller Discount"].astype(int) + merged_data["Delivery Fee"].astype(int)
#merged_data["GMV"] = merged_data["Transaction Amount"].astype(float) - merged_data["Seller Discount"].astype(float) + merged_data["Delivery Fee"].astype(float)

# Mendapatkan indeks kolom "Seller Discount" dengan cara
# menggunakan get_loc untuk mencari indeks (posisi) dari elemen Seller Discount
seller_discount_index = merged_data.columns.get_loc("Seller Discount")

# Sisipkan kolom "GMV" setelah kolom "Seller Discount" menggunakan + 1
merged_data.insert(seller_discount_index + 1, "GMV", gmv_hitung)

In [ ]:
merged_data

,Paid Date,Order Number,First Name,Last Name,Full Name,Meta Category,Product Name,Transaction Amount,Seller Discount,GMV,Sales Discount,Delivery Fee,Other Discount,Seller
0,20170724,201707240088517,elvride,aries,Elvride Aries,Babies/ Kids,Pineapple Hat Anak Ala Korea - 6M - 4Y - Unise...,300000,153000,156000,10200,9000,0,Babymaniashop
1,20170701,201707018889790,BASIR,Ninuk,Basir Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,219800,0,0,0,E-Bold
2,20170707,201707079264675,Citra,Ardi,Citra Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,35000,700,0,0,XLmystore
3,20170720,201707209945714,Dian,Renaldi,Dian Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,85000,5900,0,0,Ennwen Online Store
4,20170722,201707220002354,rizal,Tamba,Rizal Tamba,Gadget/ Komputer,Samsung Galaxy Note 5 Gold,81000,0,81000,5600,0,0,Media Gadget
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,20171201,201712012704898,Fitrah,gina,Fitrah Gina,Service/ Mokado,"Xtra Combo 12GB, 30hr",333000,300000,33000,2300,0,0,XLmystore
11996,20171203,201712032723513,Djebeng,Shinta,Djebeng Shinta,Service/ Mokado,"Xtra Combo 12GB, 30hr",280000,222500,57500,0,0,0,XLmystore
11997,20171204,201712042740205,Amik,Elan,Amik Elan,Home/ Food,Kreta - Kripik Tempe Indonesia - Rasa Jomblo d...,150000,81000,69000,4800,0,0,Kreta Chips
11998,20171207,201712072778621,Anna,asih,Anna Asih,Gadget/ Komputer,Samsung Galaxy J5 Pro Garansi Resmi Special Price,475000,400000,75000,0,0,0,Erafone.com
11999,20171205,201712052746101,nidyah,ayi,Nidyah Ayi,Service/ Mokado,[SERBU 11.12] Share Tea Cocoa Rocksalt & Chees...,475000,400000,92000,20000,17000,0,Serbu Seller

# **No 3**

In [ ]:
# Buat dictionary untuk menggabungkan kategori menjadi kelompok yang sesuai
kategori_group = {
    'Home/ Food': 'Group 1',
    'Sports/ Hobi/ Otomotif': 'Group 1',
    'Fashion': 'Group 1',
    'Beauty/ Health': 'Group 1',
    'Gadget/ Komputer': 'Group 2',
    'Elektronik': 'Group 2',
    'Service/ Mokado': 'Group 2',
    'Babies/ Kids': 'Group 2'
}

# Menerapkan pengelompokkan dan di tampung pada variabel "Group" dengan cara menggabungkan kolom Meta Category
# menjadi 2 Group berdasarkan kategori_group yang telah ditentukan
Group = merged_data['Meta Category'].map(kategori_group)

In [ ]:
Group

0        Group 2
1        Group 2
2        Group 2
3        Group 1
4        Group 2
          ...
11995    Group 2
11996    Group 2
11997    Group 1
11998    Group 2
11999    Group 2
Name: Meta Category, Length: 12000, dtype: object

In [ ]:
# Konversi kolom "Paid Date" menjadi tipe datetime  dengan format 'YYYYMMDD' menggunakan pd.to_datetime()
# errors='coerce' untuk menangani jika ada nilai yang tidak sesuai dengan format
# maka kolom "Paid Date" akan diisi dengan nilai NaN
# dan nantinya akan digunakan untuk nomor 4 & 5
merged_data['Paid Date'] = pd.to_datetime(merged_data['Paid Date'], format='%Y%m%d', errors='coerce')

# Ekstrak bulan dari kolom "Paid Date" dan simpan dalam variabel "Month" menggunakan metode .dt.to_period('M').
# untuk mempermudah agregasi data berdasarkan bulan.
Month = merged_data['Paid Date'].dt.to_period('M')

# Buat pivot table untuk jumlah total GMV per-bulan untuk setiap grup.
pivot_table_no3 = merged_data.pivot_table(values='GMV', index=Month, columns=Group, aggfunc='sum')

In [ ]:
pivot_table_no3

Meta Category    Group 1    Group 2
Paid Date
2017-07        147724300  230414100
2017-08         94599100  348790700
2017-09        263786400  191482700
2017-10        114883100  150263700
2017-11        263329200  326532200
2017-12        131366800  451421300

In [ ]:
df_pivot = pd.DataFrame(pivot_table_no3)
df_pivot

Meta Category    Group 1    Group 2
Paid Date
2017-07        147724300  230414100
2017-08         94599100  348790700
2017-09        263786400  191482700
2017-10        114883100  150263700
2017-11        263329200  326532200
2017-12        131366800  451421300

# **No 4**

In [ ]:
# Filter data untuk bulan Agustus 2017
data_agustus_2017 = merged_data[merged_data['Paid Date'].dt.strftime('%Y-%m') == '2017-08']
data_agustus_2017

,Paid Date,Order Number,First Name,Last Name,Full Name,Meta Category,Product Name,Transaction Amount,Seller Discount,GMV,Sales Discount,Delivery Fee,Other Discount,Seller
1102,2017-08-08,201708080665846,lisa,Ervin,Lisa Ervin,Babies/ Kids,Selimut Double Fleece Carters 100 cm x 75 cm -...,16000,6100,18900,0,9000,0,Venna Shop
1103,2017-08-13,201708120799765,chrysdian,Yantie,Chrysdian Yantie,Fashion,NEW ITEM // LADIES SHIRT V COLLAR // 7 Warna /...,250000,91000,169000,11100,10000,0,shop and save fashion
1104,2017-08-10,201708100736231,lidya,Ria,Lidya Ria,Service/ Mokado,Pulsa Telkomsel REG 200.000,75000,5000,70000,0,0,0,E-Bold
1105,2017-08-13,201708130817233,Novi,saif,Novi Saif,Fashion,Celana Kulot Panjang Wanita / Bahan Spandek Uk...,125000,0,125000,0,0,0,Grosir Baju Anak
1106,2017-08-29,201708291193006,gading,Febe,Gading Febe,Fashion,Ransel Wanita 816,35000,0,35000,0,0,0,hs grosir tas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5599,2017-08-23,201708231065862,Grace,Widjatmoko,Grace Widjatmoko,Service/ Mokado,Indosat REG 25000,125000,30000,95000,6600,0,0,MOBILEPULSA APP
5600,2017-08-11,201708110778087,YUWANDARI,sucipto,Yuwandari Sucipto,Babies/ Kids,Paw Patrol Parking Lot Winter Rescue,150000,45000,105000,7200,0,0,BABY WISH
5601,2017-08-06,201708060595560,Shelly,sucipto,Shelly Sucipto,Service/ Mokado,Telkomsel Data 100.000,100000,30000,70000,4800,0,0,MOBILEPULSA APP
5602,2017-08-15,201708150879873,feriyana,yasin,Feriyana Yasin,Service/ Mokado,Pulsa Bolt Isi Ulang Otomatis 100000,100000,30000,80000,4800,10000,0,MOBILEPULSA APP
5603,2017-08-29,201708271154867,rara,Rio,Rara Rio,Fashion,[ONS 0102] NEW ARRIVAL !! KEMEJA WANITA - BOYF...,100000,40000,60000,4200,0,0,SHOP THE BRANDED

In [ ]:
# Hitung total GMV per seller dengan menggunakan groupby ('Seller') untuk mengelompokkan data
# berdasarkan seller kemudian menghitung total GMV dengan menggunakan metode .sum()
seller_gmv = data_agustus_2017.groupby('Seller')['GMV'].sum().reset_index()
seller_gmv

                     Seller     GMV
0             39sK Cellular   25000
1           911 ONLINE SHOP  470000
2                     9case   51000
3                    ADshop  120000
4             AG Collection   40000
..                      ...     ...
434  www.kantongbelanja.com   76400
435                   xpart   26200
436             yes24.co.id  135300
437           yohanes store   53500
438                  zhshop   55400

[439 rows x 2 columns]

In [ ]:
# Mencari seller dengan GMV tertinggi
seller_gmv_tertinggi = seller_gmv[seller_gmv['GMV'] == seller_gmv['GMV'].max()]

# Cetak seller dengan GMV tertinggi di bulan Agustus 2017
print("Seller dengan GMV tertinggi di bulan Agustus 2017:")
print(seller_gmv_tertinggi)

Seller dengan GMV tertinggi di bulan Agustus 2017:
              Seller        GMV
207  MOBILEPULSA APP  127241500

In [ ]:
seller_gmv_tertinggi

              Seller        GMV
207  MOBILEPULSA APP  127241500

# **No 5**

In [ ]:
# Filter data untuk bulan September 2017 dengan kategori "Fashion"
data_fashion_september_2017 = merged_data[(merged_data['Paid Date'].dt.strftime('%Y-%m') == '2017-09') & (merged_data['Meta Category'] == 'Fashion')]

In [ ]:
data_fashion_september_2017

,Paid Date,Order Number,First Name,Last Name,Full Name,Meta Category,Product Name,Transaction Amount,Seller Discount,GMV,Sales Discount,Delivery Fee,Other Discount,Seller
2474,2017-09-02,201709021277460,tesya,Bayu,Tesya Bayu,Fashion,Bralette Tali 6/ Active BRA tali 6/ Black & Wh...,158000,102700,55300,0,0,0,duta shop
2476,2017-09-20,201709201670584,ladira,Anthony,Ladira Anthony,Fashion,BATIK CULLOTE - SKIRT - SKORT - Kulot Batik - ...,150000,107000,43000,3000,0,0,EVERCLOTH_ID
2479,2017-09-03,201709031301986,rusmidi,Rudi,Rusmidi Rudi,Fashion,[Future Is Now] Foldbale bag / Tas Lipat Stree...,75000,53500,21500,1500,0,0,Faith
2482,2017-09-20,201709201670331,Halimah,fajar,Halimah Fajar,Fashion,Smart Digital Wrist Watch Band Heart rate Bloo...,75000,53500,21500,1500,0,0,HAPIC Store
2642,2017-09-11,201709101490591,Najmi,Suryono,Najmi Suryono,Fashion,MUNAFIE Slimming Pants / MUNAFIE Slimming Pant...,34000,0,34000,0,0,0,Alena_Shop
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7831,2017-09-11,201709091463132,Noval,Mangaraja,Noval Mangaraja,Fashion,Singlet Pria Dewasa / Pakaian Dalam Pria / Kao...,103500,0,103500,6500,0,0,Fadfa Collections
7948,2017-09-28,201709271783320,mufaddal,ayya,Mufaddal Ayya,Fashion,kaos kaki 5 jari polos pria,51900,0,51900,2000,0,0,AG Collection
8145,2017-09-04,201709041321069,GATUTSUPRIADI,anna,Gatutsupriadi Anna,Fashion,Sepatu Pria Sneakers Nik Springblade / Sepatu ...,10400,0,10400,0,0,0,HANA PICKS
8146,2017-09-05,201709051355254,Sonny,Mahliannur,Sonny Mahliannur,Fashion,[3 Ways Bag] Atdiva Tas Ransel Selempang Simpl...,10400,0,10400,0,0,0,Tas Kpop Atdiva
8464,2017-09-18,201709181638780,Silvia,Fabiyola,Silvia Fabiyola,Fashion,CELANA PANJANG BAHAN FORMAL/CELANA KERJA PRIA ...,41600,18700,22900,0,0,0,M-line

In [ ]:
# Hitung jumlah transaksi (count) per seller
seller_transaksi_count = data_fashion_september_2017.groupby('Seller')['Order Number'].count().reset_index()
seller_transaksi_count

                  Seller  Order Number
0                1K_Shop             1
1                 ADshop             3
2                 AFalah             1
3          AG Collection             2
4                  ALIBI             1
..                   ...           ...
171              slyshop             1
172  supplier onlineshop             1
173            tokoaqila            31
174        tokopasarindo             2
175              winlans             2

[176 rows x 2 columns]

In [ ]:
# Temukan seller dengan jumlah transaksi (count) terbanyak
seller_transaksi_terbanyak = seller_transaksi_count[seller_transaksi_count['Order Number'] == seller_transaksi_count['Order Number'].max()]

# Cetak seller dengan jumlah transaksi (count) terbanyak di bulan September 2017 kategori "Fashion"
print("Seller dengan jumlah transaksi (count) terbanyak di bulan September 2017 kategori 'Fashion':")
print(seller_transaksi_terbanyak)

Seller dengan jumlah transaksi (count) terbanyak di bulan September 2017 kategori 'Fashion':
        Seller  Order Number
173  tokoaqila            31

In [ ]:
seller_transaksi_terbanyak

        Seller  Order Number
173  tokoaqila            31